apiVersion: v1
kind: Service
metadata:
  name: daphine
spec:
  selector:
    app: daphine
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: juche-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/assets
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daphine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daphine
    template:
      metadata:
        labels:
          app: daphine
      spec:
        containers:
          - name: daphine
            image: node:latest
            ports:
              - containerPort: 3000
            env:
              - name: PUPPETEER_SKIP_DOWNLOAD
                value: true
            imagePullPolicy: Always
            volumeMounts: ./
  volumes:
    - juche-pv
