---
# PersistentVolume which contains the data to be streamed
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    # Path of the data within the cluster
    path: "/mnt/assets"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - local-node

---
# PersistentVolumeClaim spec
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pv-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
# Deployment spec
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daphine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: daphine
  template:
    metadata:
      labels:
        app: daphine
    spec:
      nodeName: local-node
      containers:
        - name: daphine
          image: ghcr.io/jordojordo/daphine:latest
          ports:
            - containerPort: 3000
          env:
            - name: PUPPETEER_SKIP_DOWNLOAD
              value: "true"
            # Frontend url
            - name: CORS_ORIGIN
              value: "https://example.com"
          imagePullPolicy: Always
          volumeMounts:
            # Mount the volume for the container
            - mountPath: "./assets"
              name: example-pv
      volumes:
        - name: example-pv
          persistentVolumeClaim:
            claimName: example-pv-claim
